# LRIS slit mask

In [1]:
# imports
import numpy as np

from astropy.io import fits
from astropy.table import Table

from pypeit.spectrographs import slitmask

# Load up an example

In [2]:
tst_file = '/home/xavier/Projects/PypeIt-codes/PypeIt-development-suite/dev_algorithms/lris/slitmask/raw/LR_test_121102_mask1_trace.fits.gz'

In [3]:
hdu = fits.open(tst_file)
hdu.info()

Filename: /home/xavier/Projects/PypeIt-codes/PypeIt-development-suite/dev_algorithms/lris/slitmask/raw/LR_test_121102_mask1_trace.fits.gz
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     270   ()      
  1  VidInp2       1 ImageHDU       359   (1067, 2068)   int16 (rescales to uint16)   
  2  VidInp4       1 ImageHDU       359   (1067, 2068)   int16 (rescales to uint16)   
  3  ObjectCat     1 BinTableHDU     51   22R x 19C   [6A, K, D, D, 1A, D, D, D, 1A, D, D, D, D, D, D, D, D, 14A, K]   
  4  CatFiles      1 BinTableHDU     19   0R x 2C   [1J, 255A]   
  5  MaskDesign    1 BinTableHDU     69   1R x 17C   [1J, 68A, 68A, 68A, 19A, 1J, 1J, 68A, 68A, 68A, 1D, 1D, 8A, 1E, 1D, 19A, 1E]   
  6  DesiSlits     1 BinTableHDU     49   22R x 10C   [1J, 1J, 20A, 1D, 1D, 1A, 1E, 1E, 1E, 1E]   
  7  SlitObjMap    1 BinTableHDU     23   22R x 5C   [K, K, K, D, D]   
  8  MaskBlu       1 BinTableHDU     69   1R x 17C   [1J, 1J, 68A, 68A, 68A, 19A, 1E,

## Tables

In [4]:
desislits = Table(hdu['DesiSlits'].data)
desislits

<Table length=22>
dSlitId DesId SlitName       slitRA      ...  slitLPA    slitWid    slitWPA 
 int32  int32  str20        float64      ...  float32    float32    float32 
------- ----- -------- ----------------- ... ---------- ---------- ---------
      0     0    slit0 83.05182570861894 ... -20.449965  0.9970975  69.99877
      1     0    slit1 82.96718030685008 ... -19.659687   2.998215  69.99899
      2     0    slit2 82.97774370108544 ... -20.307901  2.9952068  69.99921
      3     0    slit3 82.94372479312733 ... -19.663515  2.9992177  69.99899
      4     0    slit4 82.99492081742261 ... -20.064709 0.99840593  69.99818
    ...   ...      ...               ... ...        ...        ...       ...
     16     0   slit16 82.95401615177157 ... -19.809109  0.9994198      70.0
     17     0   slit17   82.982139619685 ...  -20.26909   0.998417 69.999405
     18     0   slit18 83.02452522781232 ... -20.365702  0.9976037  69.99877
     19     0   slit19 83.05522689400121 ...  -20.37761 0.99716115      70.0
     20     0   slit20 83.02986693627967 ...  -20.43874 0.99745643 69.996346
     21     0   slit21 82.98568425783222 ... -19.563154 0.99920815  69.99849

In [5]:
bluslits = Table(hdu['BluSlits'].data)
bluslits

<Table length=22>
bSlitId BluId dSlitId   slitX1   ...   slitY3     slitX4     slitY4  
 int32  int32  int32   float64   ...  float64    float64    float64  
------- ----- ------- ---------- ... ---------- ---------- ----------
      0     0       0  339.09845 ... 184.808426  339.09845 184.838516
      1     0       1   61.87973 ...  89.094131  61.879692  89.081223
      2     0       2 272.864807 ...  36.582687 272.864777   36.59433
      3     0       3  56.734131 ...  36.142105  56.734093  36.129349
      4     0       4 203.677124 ... 101.922531 203.677155  101.93486
    ...   ...     ...        ... ...        ...        ...        ...
     16     0      16 110.451965 ...  40.420761 110.451965  40.385696
     17     0      17 268.698853 ...   49.44548 268.698853  49.522415
     18     0      18 307.389282 ... 133.311752 307.389282 133.370285
     19     0      19 320.144043 ... 200.730423 320.144043 200.801376
     20     0      20 333.274963 ... 136.877609 333.274994 136.962906
     21     0      21   52.56646 ... 140.836075  52.566483 140.561111

# Try loading with DEIMOS

In [6]:
smask = slitmask.load_keck_deimoslris(tst_file, 'keck_lris')

In [7]:
smask.mask_radec

(83.0057833333, 33.1521861111)

In [8]:
smask.posx_pa

340.0

## Check a few things

In [9]:
smask.corners[:,0]

array([[339.09845 , 185.559402],
       [ 61.87973 ,  86.913528],
       [272.864807,  34.428818],
       [ 56.734131,  33.960922],
       [203.677124, 102.656662],
       [169.022583, 143.884476],
       [152.365616, 102.225754],
       [129.222458, 146.409531],
       [250.329025, 152.45311 ],
       [237.692886, 158.587265],
       [213.235657, 145.743027],
       [224.602798, 181.359177],
       [144.244339, 133.366928],
       [190.804733, 170.32341 ],
       [ 97.921089, 156.805984],
       [296.226044, 150.410233],
       [110.451965,  41.108246],
       [268.698853,  50.244232],
       [307.389282, 134.091537],
       [320.144043, 201.522293],
       [333.274963, 137.684036],
       [ 52.56646 , 141.283463]])

In [10]:
smask.slitid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21], dtype=int32)

In [11]:
smask.mask

array([2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      dtype=int16)

In [12]:
smask.objects

array([['0', '0', '83.05208425000001', '33.10055497', 'gal58', '21.133',
        'I', '3.279334307858042', '0.5533701498574515'],
       ['1', '1', '82.92800254000002', '33.20285065', 'star5', '15.71',
        'I', '64.12288100592014', '66.29559388054942'],
       ['2', '2', '83.07300215000001', '33.10208921', 'star8', '17.538',
        'I', '79.76873878980466', '77.5960329151754'],
       ['3', '3', '82.96721989000002', '33.18817003', 'star10', '14.747',
        'I', '6.238064669504386', '4.065350794875176'],
       ['4', '4', '82.99531792000002', '33.13966994', 'FRBhos', '20.5',
        'I', '7.712915758594484', '3.173741906094889'],
       ['5', '5', '83.00615674000002', '33.16074453', 'gal4', '20.81',
        'I', '2.580674048760235', '12.095872073644555'],
       ['6', '6', '82.98720701000003', '33.15791278', 'gal2', '20.617',
        'I', '3.5465634651699625', '2.585094158717792'],
       ['7', '7', '83.00139446000001', '33.17448474', 'gal17', '20.708',
        'I', '7.2981412154

In [13]:
smask.onsky

array([[ 83.05182571,  33.10103233,   5.29673672,   0.99709749,
        -20.44996452],
       [ 82.96718031,  33.18815795,   3.00247765,   2.99821496,
        -19.65968704],
       [ 82.9777437 ,  33.10523642,   3.00245833,   2.99520683,
        -20.30790138],
       [ 82.94372479,  33.1831314 ,   3.00247788,   2.99921775,
        -19.66351509],
       [ 82.99492082,  33.14047494,  15.04318142,   0.99840593,
        -20.06470871],
       [ 83.00685759,  33.15901718,  20.28054428,   0.99844813,
        -19.94126892],
       [ 82.98709016,  33.15807336,   8.47273064,   0.99874413,
        -19.91879463],
       [ 83.00152514,  33.17407643,  23.20553207,   0.99863833,
        -19.81855774],
       [ 83.02348668,  33.1300557 ,  14.71805573,   0.99785751,
        -20.1867466 ],
       [ 83.02412197,  33.13549874,  15.34546375,   0.99789906,
        -20.14617348],
       [ 83.01510423,  33.14202449,  10.46251678,   0.99811065,
        -20.08309937],
       [ 83.03197546,  33.14287258,  12.963

# Fussing with corners

In [14]:
smask.corners.shape

(22, 4, 2)

In [15]:
smask.corners[7,...]

array([[129.222458, 146.409531],
       [112.444939, 146.462692],
       [112.444962, 145.740646],
       [129.222473, 145.687546]])

## Increasing in x?

In [16]:
smask.corners[:,0,0]

array([339.09845 ,  61.87973 , 272.864807,  56.734131, 203.677124,
       169.022583, 152.365616, 129.222458, 250.329025, 237.692886,
       213.235657, 224.602798, 144.244339, 190.804733,  97.921089,
       296.226044, 110.451965, 268.698853, 307.389282, 320.144043,
       333.274963,  52.56646 ])

In [17]:
smask.corners[:,0,1]

array([185.559402,  86.913528,  34.428818,  33.960922, 102.656662,
       143.884476, 102.225754, 146.409531, 152.45311 , 158.587265,
       145.743027, 181.359177, 133.366928, 170.32341 , 156.805984,
       150.410233,  41.108246,  50.244232, 134.091537, 201.522293,
       137.684036, 141.283463])

In [18]:
x_order = np.argsort(smask.corners[:,1,0])

In [19]:
smask.corners[x_order,0,0]

array([ 52.56646 ,  56.734131,  61.87973 ,  97.921089, 110.451965,
       129.222458, 144.244339, 152.365616, 169.022583, 190.804733,
       203.677124, 213.235657, 224.602798, 237.692886, 250.329025,
       268.698853, 272.864807, 296.226044, 307.389282, 320.144043,
       333.274963, 339.09845 ])

In [20]:
x_order[-1]

0

In [21]:
smask.objects[0,:]

array(['0', '0', '83.05208425000001', '33.10055497', 'gal58', '21.133',
       'I', '3.279334307858042', '0.5533701498574515'], dtype='<U32')

In [24]:
smask.objects[21,:]

array(['21', '21', '82.98695610000001', '33.20166688', 'gal43', '20.465',
       'I', '25.941910791806432', '10.164959368434072'], dtype='<U32')

----

# Mask Design

In [35]:
Table(hdu['MaskDesign'].data)

<Table length=1>
DesId        DesName        ...       DATE_PNT      LST_PNT 
int32         str68         ...        str19        float32 
----- --------------------- ... ------------------- --------
    0 frb121102_mask2.file3 ... 2000-01-01T05:00:00 83.00765

## RA

In [37]:
smask.onsky[:,0]

array([82.93779765, 82.96722232, 83.07389766, 83.07527971, 83.00983276,
       82.9785294 , 82.94376722, 83.00308322, 82.9909731 , 83.01743658,
       83.02639843, 83.04926203, 82.97033667, 83.001686  , 83.0399412 ,
       83.03646298, 83.07130494, 83.04861165, 83.05894575, 82.93625323,
       83.0237547 , 83.06385427, 83.08086559])

## Dec

In [39]:
smask.onsky[:,1]

array([33.11788953, 33.18815507, 33.14151319, 33.1617532 , 33.16019118,
       33.16688312, 33.18312512, 33.16516697, 33.17392007, 33.14220542,
       33.14260651, 33.14859547, 33.17685819, 33.18487748, 33.1246123 ,
       33.13264118, 33.1617158 , 33.12465476, 33.14944078, 33.1289471 ,
       33.10120439, 33.14804429, 33.15241174])