# LRIS slit mask

In [1]:
# imports
import numpy as np

from astropy.io import fits
from astropy.table import Table

from pypeit.spectrographs import slitmask

# Load up an example

In [49]:
tst_file = '/home/xavier/Projects/PypeIt-codes/PypeIt-development-suite/dev_algorithms/lris/slitmask/raw/LR_test_190714_mask2_trace.fits.gz'

In [50]:
hdu = fits.open(tst_file)
hdu.info()

Filename: /home/xavier/Projects/PypeIt-codes/PypeIt-development-suite/dev_algorithms/lris/slitmask/raw/LR_test_190714_mask2_trace.fits.gz
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     270   ()      
  1  VidInp2       1 ImageHDU       359   (1067, 2068)   int16 (rescales to uint16)   
  2  VidInp4       1 ImageHDU       359   (1067, 2068)   int16 (rescales to uint16)   
  3  ObjectCat     1 BinTableHDU     51   25R x 19C   [6A, K, D, D, 1A, D, D, D, 1A, D, D, D, D, D, D, D, D, 14A, K]   
  4  CatFiles      1 BinTableHDU     19   0R x 2C   [1J, 255A]   
  5  MaskDesign    1 BinTableHDU     69   1R x 17C   [1J, 68A, 68A, 68A, 19A, 1J, 1J, 68A, 68A, 68A, 1D, 1D, 8A, 1E, 1D, 19A, 1E]   
  6  DesiSlits     1 BinTableHDU     49   25R x 10C   [1J, 1J, 20A, 1D, 1D, 1A, 1E, 1E, 1E, 1E]   
  7  SlitObjMap    1 BinTableHDU     23   25R x 5C   [K, K, K, D, D]   
  8  MaskBlu       1 BinTableHDU     69   1R x 17C   [1J, 1J, 68A, 68A, 68A, 19A, 1E,

## Tables

In [51]:
desislits = Table(hdu['DesiSlits'].data)
desislits

<Table length=25>
dSlitId DesId SlitName       slitRA             slitDec       ...  slitLen    slitLPA   slitWid    slitWPA 
 int32  int32  str20        float64             float64       ...  float32    float32   float32    float32 
------- ----- -------- ------------------ ------------------- ... ---------- --------- ---------- ---------
      0     0    slit0 183.92207514243304 -13.070334597502294 ...  3.0025303 59.545315  2.9924316 149.99878
      1     0    slit1 183.91593254290657 -13.037196089125626 ...  3.0025065   59.6043  2.9944468  149.9988
      2     0    slit2 184.00503849510343 -13.059785992506692 ...   3.002448  60.15949   2.994648  149.9988
      3     0    slit3 183.98996234295862 -13.040812814769433 ...  14.731228   60.1118  0.9985111 149.99814
      4     0    slit4 184.02647939802435 -13.039654866804073 ...   26.42586 60.371243  0.9987434 149.99846
      5     0    slit5 183.97401109662334 -13.022105208651029 ...   9.298538  60.05761 0.99878633 149.99876
      6     0    slit6 183.99199434203294 -13.021684087762127 ...  14.773202 60.185234  0.9989129     150.0
      7     0    slit7 183.97164508316274   -13.0298594316524 ...   27.52903 60.017307 0.99859613 149.99881
      8     0    slit8 183.95500515333364 -13.037758697240788 ...   32.45935  59.87632   0.998343 149.99817
      9     0    slit9 183.92429505134717 -13.046291992869632 ...   9.557008 59.634968  0.9979841 149.99757
    ...   ...      ...                ...                 ... ...        ...       ...        ...       ...
     14     0   slit14   184.009099240518 -13.025370519497194 ...  22.220497 60.293537  0.9989336 149.99817
     15     0   slit15   184.025595477487 -13.025756546356597 ... 12.8108015 60.407864 0.99903876 149.99854
     16     0   slit16  184.0175540623584 -13.004623363877817 ...   8.989721 60.416588  0.9994191 149.99817
     17     0   slit17 183.95501943434564  -13.07151546669452 ... 10.8778305 59.772224  0.9976037 149.99876
     18     0   slit18 183.92650769843883 -13.043225255267608 ...   9.433918 59.659756  0.9980788 149.99876
     19     0   slit19  184.0351228016422 -13.020519076379763 ...   7.069542 60.490738 0.99920815 149.99821
     20     0   slit20 183.96271381720615 -13.070620196179464 ...   33.61691  59.82896   0.997731 149.99881
     21     0   slit21 183.93942492454934 -13.058532042261335 ...    8.42839 59.703014  0.9977939 149.99876
     22     0   slit22 183.92775152991237  -13.03251455728324 ...   8.841123 59.701153  0.9983216 149.99876
     23     0   slit23 184.03254100259292 -13.022762851938852 ...  11.204954 60.465782 0.99914455 149.99817
     24     0   slit24  183.9082211449927 -13.035569082956373 ...  32.519108 59.555153 0.99815285 149.99881

In [52]:
bluslits = Table(hdu['BluSlits'].data)
bluslits

<Table length=25>
bSlitId BluId dSlitId   slitX1     slitY1   ...   slitY2     slitX3     slitY3     slitX4     slitY4  
 int32  int32  int32   float64    float64   ...  float64    float64    float64    float64    float64  
------- ----- ------- ---------- ---------- ... ---------- ---------- ---------- ---------- ----------
      0     0       0 333.569763 130.780899 ... 130.763657 331.398956   132.9272 333.569702 132.944412
      1     0       1 303.900085  47.452805 ...   47.43779 301.729279  49.602798 303.900024  49.617767
      2     0       2  137.45639 212.316666 ... 212.322708 135.285583 214.487839 137.456345 214.481796
      3     0       3 150.103088 151.350082 ... 151.370895 139.452454 150.648941 150.103104 150.628189
      4     0       4  72.551094 195.732437 ... 195.856277  53.445618  195.13414  72.551117 195.010391
      5     0       5 158.822021  88.421677 ...  88.428452 152.099197  87.706314 158.822037   87.69957
      6     0       6 120.717033 110.545242 ... 110.579819 110.036064 109.857559 120.717033 109.823074
      7     0       7 180.720154 103.011093 ... 103.017136 160.816681  102.29512 180.720169 102.289139
      8     0       8 229.378494  99.755417 ...  99.704819 205.910461  98.982956  229.37851  99.033676
      9     0       9 299.733795  80.219925 ...  80.175919 292.824249  79.454361 299.733826  79.498398
    ...   ...     ...        ...        ... ...        ...        ...        ...        ...        ...
     14     0      14  90.612259 140.929733 ...  141.01207  74.547073  140.28981  90.612282 140.207535
     15     0      15  51.451302   163.1465 ... 163.212448  42.189346 162.490128  51.451324  162.42421
     16     0      16   40.19548 104.878952 ... 104.926224  33.696106 104.203629  40.195511 104.156387
     17     0      17 265.536438 176.564468 ... 176.533218 257.671844 175.811935 265.536469 175.843216
     18     0      18 290.829376  76.023483 ...  75.983002 284.008789  75.261368 290.829407  75.301895
     19     0      19  21.604248 163.666336 ... 163.710129  16.493179 162.987686  21.604263 162.943924
     20     0      20 255.676773 184.322403 ... 184.249893 231.371872 183.528488 255.676788 183.601089
     21     0      21 282.012909 127.240952 ... 127.209396 275.919281 126.487961 282.012909 126.519577
     22     0      22  273.92572  53.181839 ...  53.148514 267.533691  52.426712 273.925751  52.460068
     23     0      23  31.700027 165.378036 ... 165.443924  23.599136 164.721512  31.700058 164.655685
     24     0      24 329.405823  35.543076 ...   35.36058 305.895233   34.63887 329.405853  34.821457

# Try loading with DEIMOS

In [74]:
smask = slitmask.load_keck_deimoslris(tst_file, 'keck_lris')

In [75]:
smask.mask_radec

(183.975716667, -13.0420333333)

In [76]:
smask.posx_pa

60.0

## Check a few things

In [77]:
smask.corners[:,0]

array([[333.569763, 130.780899],
       [303.900085,  47.452805],
       [137.45639 , 212.316666],
       [150.103088, 151.350082],
       [ 72.551094, 195.732437],
       [158.822021,  88.421677],
       [120.717033, 110.545242],
       [180.720154, 103.011093],
       [229.378494,  99.755417],
       [299.733795,  80.219925],
       [108.041054, 114.303879],
       [133.291504, 168.598709],
       [ 98.805061, 117.030563],
       [203.916153,  65.765686],
       [ 90.612259, 140.929733],
       [ 51.451302, 163.1465  ],
       [ 40.19548 , 104.878952],
       [265.536438, 176.564468],
       [290.829376,  76.023483],
       [ 21.604248, 163.666336],
       [255.676773, 184.322403],
       [282.012909, 127.240952],
       [273.92572 ,  53.181839],
       [ 31.700027, 165.378036],
       [329.405823,  35.543076]])

In [57]:
smask.slitid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [58]:
smask.mask

array([1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2], dtype=int16)

In [78]:
smask.objects

array([['0', '0', '183.92211101000007', '-13.07029395', 'star3',
        '14.011', 'I', '1.6827191261167456', '1.3189443008769661'],
       ['1', '1', '183.91596834000003', '-13.03715467', 'star4',
        '14.298', 'I', '1.6840965813836655', '1.3177220481207805'],
       ['2', '2', '184.00507430000005', '-13.05974667', 'star6',
        '14.894', 'I', '1.6809172421081853', '1.3212744225502582'],
       ['3', '3', '183.98954220000002', '-13.04103016', 'gal13',
        '19.981', 'I', '5.690244957997731', '9.024592270445433'],
       ['4', '4', '184.02767930000002', '-13.03896142', 'gal36',
        '22.386', 'I', '18.089816148536666', '8.30426999807618'],
       ['5', '5', '183.97383420000003', '-13.02218565', 'gal2', '21.779',
        'I', '3.9615555176099693', '5.325782082841692'],
       ['6', '6', '183.99243883000003', '-13.02141494', 'gal5', '21.681',
        'I', '9.212967192530362', '5.543814969267647'],
       ['7', '7', '183.97414279000003', '-13.02843435', 'gal4', '20.981',
    

In [79]:
smask.onsky

array([[183.92207514, -13.0703346 ,   3.00253034,   2.99243164,
         59.54531479],
       [183.91593254, -13.03719609,   3.00250649,   2.99444675,
         59.60430145],
       [184.0050385 , -13.05978599,   3.00244808,   2.99464798,
         60.15948868],
       [183.98996234, -13.04081281,  14.73122787,   0.99851108,
         60.11180115],
       [184.0264794 , -13.03965487,  26.42585945,   0.99874341,
         60.37124252],
       [183.9740111 , -13.02210521,   9.29853821,   0.99878633,
         60.05760956],
       [183.99199434, -13.02168409,  14.77320194,   0.99891287,
         60.18523407],
       [183.97164508, -13.02985943,  27.52902985,   0.99859613,
         60.01730728],
       [183.95500515, -13.0377587 ,  32.45935059,   0.99834299,
         59.87631989],
       [183.92429505, -13.04629199,   9.55700779,   0.99798411,
         59.6349678 ],
       [183.99645764, -13.02080636,  10.01528931,   0.99895507,
         60.21913528],
       [183.99905218, -13.04327143,  14.634

# Fussing with corners

In [61]:
smask.corners.shape

(25, 4, 2)

In [62]:
smask.corners[7,...]

array([[180.720154, 103.011093],
       [160.816666, 103.017136],
       [160.816681, 102.29512 ],
       [180.720169, 102.289139]])

## Increasing in x?

In [63]:
smask.corners[:,0,0]

array([333.569763, 303.900085, 137.45639 , 150.103088,  72.551094,
       158.822021, 120.717033, 180.720154, 229.378494, 299.733795,
       108.041054, 133.291504,  98.805061, 203.916153,  90.612259,
        51.451302,  40.19548 , 265.536438, 290.829376,  21.604248,
       255.676773, 282.012909, 273.92572 ,  31.700027, 329.405823])

In [64]:
smask.corners[:,0,1]

array([130.780899,  47.452805, 212.316666, 151.350082, 195.732437,
        88.421677, 110.545242, 103.011093,  99.755417,  80.219925,
       114.303879, 168.598709, 117.030563,  65.765686, 140.929733,
       163.1465  , 104.878952, 176.564468,  76.023483, 163.666336,
       184.322403, 127.240952,  53.181839, 165.378036,  35.543076])

In [65]:
x_order = np.argsort(smask.corners[:,1,0])

In [66]:
smask.corners[x_order,0,0]

array([ 21.604248,  31.700027,  40.19548 ,  51.451302,  72.551094,
        90.612259,  98.805061, 108.041054, 120.717033, 133.291504,
       137.45639 , 150.103088, 158.822021, 180.720154, 203.916153,
       229.378494, 255.676773, 265.536438, 273.92572 , 282.012909,
       290.829376, 299.733795, 303.900085, 329.405823, 333.569763])

In [67]:
x_order[-1]

0

In [68]:
smask.objects[0,:]

array(['0', '0', '183.92211101000007', '-13.07029395', 'star3', '14.011',
       'I', '1.3189443008769661', '1.6827191261167456'], dtype='<U32')

In [80]:
smask.objects[-1,:]

array(['24', '24', '183.91089143000005', '-13.03404619', 'gal61',
       '21.275', 'I', '27.090037371147393', '5.387180033125098'],
      dtype='<U32')

----

# Mask Design

In [70]:
Table(hdu['MaskDesign'].data)

<Table length=1>
DesId        DesName                    DesAuth             ...  PA_PNT       DATE_PNT       LST_PNT 
int32         str68                      str68              ... float64        str19         float32 
----- --------------------- ------------------------------- ... ------- ------------------- ---------
    0 frb190714_mask2.file3 J. R. Troll <shassans@ucsc.edu> ...    60.0 2000-01-01T05:00:00 183.97572

## RA

In [71]:
smask.onsky[:,0]

array([183.92207514, 183.91593254, 184.0050385 , 183.98996234,
       184.0264794 , 183.9740111 , 183.99199434, 183.97164508,
       183.95500515, 183.92429505, 183.99645764, 183.99905218,
       183.99995563, 183.95666551, 184.00909924, 184.02559548,
       184.01755406, 183.95501943, 183.9265077 , 184.0351228 ,
       183.96271382, 183.93942492, 183.92775153, 184.032541  ,
       183.90822114])

## Dec

In [72]:
smask.onsky[:,1]

array([-13.0703346 , -13.03719609, -13.05978599, -13.04081281,
       -13.03965487, -13.02210521, -13.02168409, -13.02985943,
       -13.0377587 , -13.04629199, -13.02080636, -13.04327143,
       -13.02002067, -13.02189083, -13.02537052, -13.02575655,
       -13.00462336, -13.07151547, -13.04322526, -13.02051908,
       -13.0706202 , -13.05853204, -13.03251456, -13.02276285,
       -13.03556908])

----

# Objects

In [81]:
smask.objects

array([['0', '0', '183.92211101000007', '-13.07029395', 'star3',
        '14.011', 'I', '1.6827191261167456', '1.3189443008769661'],
       ['1', '1', '183.91596834000003', '-13.03715467', 'star4',
        '14.298', 'I', '1.6840965813836655', '1.3177220481207805'],
       ['2', '2', '184.00507430000005', '-13.05974667', 'star6',
        '14.894', 'I', '1.6809172421081853', '1.3212744225502582'],
       ['3', '3', '183.98954220000002', '-13.04103016', 'gal13',
        '19.981', 'I', '5.690244957997731', '9.024592270445433'],
       ['4', '4', '184.02767930000002', '-13.03896142', 'gal36',
        '22.386', 'I', '18.089816148536666', '8.30426999807618'],
       ['5', '5', '183.97383420000003', '-13.02218565', 'gal2', '21.779',
        'I', '3.9615555176099693', '5.325782082841692'],
       ['6', '6', '183.99243883000003', '-13.02141494', 'gal5', '21.681',
        'I', '9.212967192530362', '5.543814969267647'],
       ['7', '7', '183.97414279000003', '-13.02843435', 'gal4', '20.981',
    