# Developing SpecObjs [v3]
    v2 -- Converting specobjs to be a numpy array instead of a list
    v2.1 -- Set method
    v3 - Revamped

In [4]:
# imports
import numpy as np
from importlib import reload

from pypeit import newspecobjs
from pypeit import newspecobj

## Instantiate a null

In [2]:
sobjs = newspecobjs.SpecObjs()

In [3]:
sobjs

<SpecObjs:Empty SpecObjs>

## Now with a few specobj

### Make em

In [5]:
reload(newspecobjs)
newsobj1 = newspecobj.SpecObj('MultiSlit', 1, slitid=0)
newsobj2 = newspecobj.SpecObj('MultiSlit', 1, slitid=1)
#
newsobjs = newspecobjs.SpecObjs(specobjs=[newsobj1, newsobj2])

### Attributes

In [6]:
newsobjs.PYPELINE

array(['MultiSlit', 'MultiSlit'], dtype='<U9')

### Add em

In [8]:
sobjs.specobjs = np.array([newsobj1, newsobj2])

## Call me

In [9]:
sobjs[0]['PYPELINE']

'MultiSlit'

In [10]:
sobjs['SLITID']

array([0, 1])

## Add a new obj

In [12]:
sobj3 = newspecobj.SpecObj('MultiSlit', 1, slitid=2)
sobj3

<SpecObj: SPAT-----SLIT0002-DET01>

In [13]:
sobjs.add_sobj(sobj3)

In [14]:
sobjs

<SpecObjs:
  <SpecObj: SPAT-----SLIT0000-DET01> 
  <SpecObj: SPAT-----SLIT0001-DET01> 
  <SpecObj: SPAT-----SLIT0002-DET01> 
>

## Remove an obj

In [15]:
sobjs.remove_sobj(2)

In [16]:
sobjs

<SpecObjs:
  <SpecObj: SPAT-----SLIT0000-DET01> 
  <SpecObj: SPAT-----SLIT0001-DET01> 
>

## Set

### As item

In [18]:
sobjs.DET = 3

In [19]:
sobjs.DET

array([3, 3])

### With slice

In [22]:
sobjs[1:2].DET = 2
sobjs.DET

array([3, 2])