# Developing SpecObjs [v2.1]
    v2 -- Converting specobjs to be a numpy array instead of a list
    v2.1 -- Set method

In [1]:
# imports
import numpy as np
from importlib import reload

from pypeit import specobjs

## Instantiate a null

In [2]:
sobjs = specobjs.SpecObjs()

In [3]:
sobjs

<Table length=0>
<No columns>

## Now with a few specobj

### Make em

In [4]:
shape = (1024,2048)

In [5]:
sobj1 = specobjs.SpecObj(shape, (800., 810.), 1240.)
sobj1

<Table length=1>
 shape [2]   slit_spat_pos [2] slit_spec_pos ... boxcar optimal
   int64          float64         float64    ... object  object
------------ ----------------- ------------- ... ------ -------
1024 .. 2048    800.0 .. 810.0        1240.0 ...     {}      {}

In [6]:
sobj2 = specobjs.SpecObj(shape, (400., 430.), 1240.)
sobj2

<Table length=1>
 shape [2]   slit_spat_pos [2] slit_spec_pos ... boxcar optimal
   int64          float64         float64    ... object  object
------------ ----------------- ------------- ... ------ -------
1024 .. 2048    400.0 .. 430.0        1240.0 ...     {}      {}

In [7]:
sobj1.__dict__

{'HAND_EXTRACT_DET': None,
 'HAND_EXTRACT_FLAG': False,
 'HAND_EXTRACT_FWHM': None,
 'HAND_EXTRACT_SPAT': None,
 'HAND_EXTRACT_SPEC': None,
 'boxcar': {},
 'config': None,
 'det': 1,
 'fwhm': None,
 'idx': 'O-----S999-D01-I0001',
 'maskwidth': None,
 'maxcol': None,
 'mincol': None,
 'objid': None,
 'objtype': 'unknown',
 'optimal': {},
 'scidx': 1,
 'setup': None,
 'shape': (1024, 2048),
 'slit_spat_pos': (800.0, 810.0),
 'slit_spec_pos': 1240.0,
 'slitid': 999,
 'smash_peakflux': None,
 'spat_fracpos': None,
 'spat_pixpos': None,
 'trace_spat': None,
 'trace_spec': None}

### Add em

In [8]:
sobjs.specobjs = np.array([sobj1, sobj2])
sobjs.build_summary()

In [9]:
sobjs

<Table length=2>
 shape [2]   slit_spat_pos [2] slit_spec_pos ... boxcar optimal
   int64          float64         float64    ... object  object
------------ ----------------- ------------- ... ------ -------
1024 .. 2048    800.0 .. 810.0        1240.0 ...     {}      {}
1024 .. 2048    400.0 .. 430.0        1240.0 ...     {}      {}

## Call me

In [10]:
sobjs[0]['shape']

(1024, 2048)

In [11]:
sobjs['shape']

array([[1024, 2048],
       [1024, 2048]])

## Add a new obj

In [12]:
sobj3 = specobjs.SpecObj(shape, (200., 220.), 1240.)
sobj3

<Table length=1>
 shape [2]   slit_spat_pos [2] slit_spec_pos ... boxcar optimal
   int64          float64         float64    ... object  object
------------ ----------------- ------------- ... ------ -------
1024 .. 2048    200.0 .. 220.0        1240.0 ...     {}      {}

In [13]:
sobjs.add_sobj(sobj3)

In [14]:
sobjs

<Table length=3>
 shape [2]   slit_spat_pos [2] slit_spec_pos ... boxcar optimal
   int64          float64         float64    ... object  object
------------ ----------------- ------------- ... ------ -------
1024 .. 2048    800.0 .. 810.0        1240.0 ...     {}      {}
1024 .. 2048    400.0 .. 430.0        1240.0 ...     {}      {}
1024 .. 2048    200.0 .. 220.0        1240.0 ...     {}      {}

## Remove an obj

In [15]:
sobjs.remove_sobj(2)

In [16]:
sobjs

<Table length=2>
 shape [2]   slit_spat_pos [2] slit_spec_pos ... boxcar optimal
   int64          float64         float64    ... object  object
------------ ----------------- ------------- ... ------ -------
1024 .. 2048    800.0 .. 810.0        1240.0 ...     {}      {}
1024 .. 2048    400.0 .. 430.0        1240.0 ...     {}      {}

## Set

### As item

In [17]:
sobjs['det'] = 3

In [18]:
sobjs.det

array([3, 3])

### With slice

In [19]:
sobjs[1:2]['det'] = 2
sobjs.det

array([3, 2])

### Underlying method

In [20]:
sobjs.set(0, 'det', 3)
sobjs.set(slice(1,2), 'det', 1)

In [21]:
sobjs.det

array([3, 1])

----